### PR TITLE
Document admin client functionalities in a specific documentation page

### PR DESCRIPTION
**Pull request by BenFradet**
When I first looked around I didn't know there were functionalities around the admin client so I thought I'd create a small documentation page.

However I don't know / wasn't able to find out how the pages are organized on the website.

### CODE REVIEW

**Comment by vlovgr** [comment]
Thanks for this @BenFradet!

If you add the page identifier (`admin`) to the list in [`website/sidebars.json`](https://github.com/ovotech/fs2-kafka/blob/master/website/sidebars.json), a link to the page will show up in the left documentation sidebar on the website.

If you want to preview your changes with live reloading on changes, you can use the following.

```bash
# Shell 1
sbt "~docs/run"

# Shell 2
cd website
yarn install
yarn start run
```

We're using mdoc and docusaurus, outlined briefly here: https://scalameta.org/mdoc/docs/docusaurus.html.

**Comment by BenFradet** [comment]
excellent, thanks! don't know how I missed the `website` folder...

**Comment by vlovgr** [comment]
Thanks again @BenFradet! I've added a section on 'default settings', and done some minor changes to make it more consistent with the rest of the documentation.

**Comment by BenFradet** [comment]
cool thanks :+1:

**Pull request merged**
